### ISSUE TITLE
GoogleHome cannot load/SSL error

### ISSUE THREAD

**Issue by collateral87** [leikoilja/ha-google-home#876] opened 2024-06-07 22:52 UTC
I use version v1.11.0 in homeassistant 2024.6.1.

Yesterday the integration worked like expected, today i get this strange error:
![Screenshot_20240607_235713_Home Assistant.jpg](https://github.com/leikoilja/ha-google-home/assets/97076257/c283b137-7127-4b8c-9fcb-59d8a01e04c0)

I deleted the integration and tried to setup again (with app password), then i get "password or username incorrect".

**Comment by corgana** [comment] 2024-06-07 23:07
Same issue. Tried deleting/re-adding too and got the same error.

**Comment by cdn4lf** [comment] 2024-06-07 23:47
I thought I was going crazy.  Same issue here.  Enabled debugging, but I still only get the error above.

Tried rolling my password and token, no change.

**Comment by robertoleonardo** [comment] 2024-06-07 23:54
same issue - and i thought maybe i needed a new master token and tried to run that python script to get one, and it seems to be giving the same issue.  so i think it's probably google server side.

**Comment by cdn4lf** [comment] 2024-06-07 23:57
@robertoleonardo, Docker container returned a token without any issues

**Comment by pqpxo** [comment] 2024-06-07 23:57
Same issue. I'm getting SSL errors for what looks like the domain 'android.clients.google.com'

I've spent a few hours trying work arounds and different methods with no luck.

`requests.exceptions.SSLError: HTTPSConnectionPool(host='android.clients.google.com', port=443): Max retries exceeded with url: /auth (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))`

**Comment by cameronjust** [comment] 2024-06-08 00:25
Seeing the same error here. 

Home Assistant can still trigger Google Home devices to play sounds/voice prompts when automations trigger though.

**Comment by sp3cialck** [comment] 2024-06-08 02:09
Same here, and when i tried to login again after removing the integration, it says, invalid master token!

**Comment by Gtwizzy** [comment] 2024-06-08 05:55
Same Issue here unfortunately

**Comment by Jantjuhhh** [comment] 2024-06-08 07:34
Same issue here.

**Comment by BenAChilds** [comment] 2024-06-08 07:48
+1 for me

**Comment by tvvalbonne** [comment] 2024-06-08 08:04
+1

**Comment by lobolobo** [comment] 2024-06-08 09:15
+1

**Comment by xs2erwin** [comment] 2024-06-08 09:42
+1

**Comment by KapJI** [comment] 2024-06-08 09:53
I'm unable to repro this issue on any of my setups (local macos, linux debian, haos on x86 or arm64). But it's likely this can be fixed by adding `context.load_default_certs()` (https://github.com/simon-weber/gpsoauth/issues/57).

If you can repro this issue, please submit a PR to gpsoauth.

**Comment by kwkid** [comment] 2024-06-08 11:34
My issue started after installing 2024.6.1…perhaps just a coincidence

**Comment by MalteMatthey** [comment] 2024-06-08 11:37
Yes, the issue appears to be with version 2024.6.1. After downgrading to version 2024.6.0, the problem no longer persists.

**Comment by xs2erwin** [comment] 2024-06-08 16:07
> Yes, the issue appears to be with version 2024.6.1. After downgrading to version 2024.6.0, the problem no longer persists.

Same here. Got back to 2024.6.0 and lost the problem.

**Comment by psleutel** [comment] 2024-06-08 16:21
Yes, the issue appears to be with version 2024.6.1. After downgrading to version 2024.6.0, the problem no longer persists.

**Comment by ctsdad** [comment] 2024-06-08 16:25
Hey I am having the same issue . Can anyone advise on how to roll back to the old version?
What  are  the chances this will be fixed through an update soon?

Thanks in advance for any help given

**Comment by m3tc0n** [comment] 2024-06-08 16:33
> Hey I am having the same issue . Can anyone advise on how to roll back to the old version?
> What  are  the chances this will be fixed through an update soon?
> 
> Thanks in advance for any help given

Ssh into HA and use the following command: ha core update --version 2024.6.0

**Comment by ejpenney** [comment] 2024-06-08 16:37
> I'm unable to repro this issue on any of my setups (local macos, linux debian, haos on x86 or arm64). But it's likely this can be fixed by adding `context.load_default_certs()` ([simon-weber/gpsoauth#57](https://github.com/simon-weber/gpsoauth/issues/57)).
> 
> If you can repro this issue, please submit a PR to gpsoauth.
> 
> **And stop posting "+1" if you can't to provide any useful context. You can hit "subscribe" button to get the updates about this issue.**

I added that line to gpsoauth as recommended and it works, issue went away.  PR created [here](https://github.com/simon-weber/gpsoauth/pull/67)

**Comment by ctsdad** [comment] 2024-06-08 16:39
> > Hey I am having the same issue . Can anyone advise on how to roll back to the old version?
> > What  are  the chances this will be fixed through an update soon?
> > Thanks in advance for any help given
> 
> Ssh into HA and use the following command: ha core update --version 2024.6.0

Thanks!

**Comment by Jantjuhhh** [comment] 2024-06-08 16:45
> > I'm unable to repro this issue on any of my setups (local macos, linux debian, haos on x86 or arm64). But it's likely this can be fixed by adding `context.load_default_certs()` ([simon-weber/gpsoauth#57](https://github.com/simon-weber/gpsoauth/issues/57)).
> > If you can repro this issue, please submit a PR to gpsoauth.
> > **And stop posting "+1" if you can't to provide any useful context. You can hit "subscribe" button to get the updates about this issue.**
> 
> I added that line to gpsoauth as recommended and it works, issue went away. PR created [here](https://github.com/simon-weber/gpsoauth/pull/67)

in what file do you put this ?

**Comment by ejpenney** [comment] 2024-06-08 17:13
It's in the PR I linked. site-packages/gpsoauth/__init__.py

I'm being intentionally vague, because if that doesn't make sense to you I would recommend you revert and wait for the updates. Modifying Python libs in site-packages requires a small amount of expertise, and the method will vary a lot depending on your setup.

**Comment by michaeldjjohnson** [comment] 2024-06-09 20:16
I would be grateful to hear of how this can be resolved. I am also unable to obtain a master token. How did everyone here get theirs? Thank you kindly

**Comment by viertel97** [comment] 2024-06-09 21:34
> I would be grateful to hear of how this can be resolved. I am also unable to obtain a master token. How did everyone here get theirs? Thank you kindly

https://github.com/simon-weber/gpsoauth#alternative-flow
With this you can get the master token

**Comment by ejpenney** [comment] 2024-06-10 02:09
Gpsoauth 1.1.1 was released, not sure what needs to happen here, will the new release get picked up without changes?

**Comment by Omnipius** [comment] 2024-06-10 05:23
Hard to say. Even with forcing gpsoauth==1.1.1 to be installed on integration setup, I had to use the alternate flow above to get a viable master token. No other approach was effective.

**Comment by KapJI** [comment] 2024-06-10 09:59
Version 1.11.1 was released. It should include the fix to SSL verification.

**Comment by tsew2674** [comment] 2024-06-10 11:41
For what it's worth, everything started working for me again after installing 1.11.1. I didn't have to mess with my master token at all, however, I never tried to re-authenticate when the SSL error was present, so that that may be part of it. Thanks all for such a quick resolution!

**Comment by cimco1990** [comment] 2024-06-10 11:53
Is there a way to update manualy? HA is not offering an update to 1.11.1.

**Comment by tsew2674** [comment] 2024-06-10 12:06
> Is there a way to update manualy? HA is not offering an update to 1.11.1.

In HACS, select redownload and you should see 1.11.1 as an option

**Closed** 2024-06-10 12:44 UTC

**Comment by pista73** [comment] 2024-06-10 12:48
> > C'è un modo per aggiornare manualmente? HA non offre un aggiornamento alla versione 1.11.1.
> 
> In HACS, seleziona riscarica e dovresti vedere 1.11.1 come opzione



solved...thanks a lot

**Comment by collateral87** [comment] 2024-06-10 13:04
I installed version 1.11.1 and running HA version 2024.6.1 and still cannot setup the integration. Have i miss something?

**Comment by corgana** [comment] 2024-06-10 13:19
I was still unable to log in (generic invalid username/password error) but restored a backup where I was logged in, updated the integration, then updated HA and it appears to be working.

**Comment by collateral87** [comment] 2024-06-10 13:21
That means reauthentication doesnt work at the moment?
What must happen, that i will work again?

**Comment by robertoleonardo** [comment] 2024-06-10 16:14
i think it might help if you update the integration before upgrading to ha os 2024.6.1 -- i had downgrowneded to 2024.6 when the issue started a few days ago, and only updated to .1 after i saw the google home update in hacs and it seems to be working fine.



--
rob lee
m: 310.431.1619
________________________________

**Comment by collateral87** [comment] 2024-06-11 06:52
I didn't want to restore a backup that was so long ago. I have found another way, which I would like to show here for other people who also don't want to restore a backup but have one:
I wnt into the backup directory --> homeassistant --> data --> .storage --> config_entries. In this file i searched for google_home and then copied out the master token here. With these, I was able to restore the integration in version 2024.6.1 as well.

**Comment by michaeldjjohnson** [comment] 2024-06-11 07:51
I now have this issue. I think I need to delete all elements and start again. Could someone guide me here please.
![Error](https://github.com/leikoilja/ha-google-home/assets/109438168/3753536e-bd39-4627-955c-4d4f59b381c3)

Thank you

**Comment by michaeldjjohnson** [comment] 2024-06-12 09:18
How do I delete my setup and start all over again please?
