### ISSUE TITLE
Component unable to load after upgrading to v1.9.13

### ISSUE THREAD

**Issue by DerekF35** [leikoilja/ha-google-home#567] opened 2022-07-05 16:35 UTC
I've been banging my head against the wall for a few days.  v1.9.12 works fine when I downgrade, however upgrading to v1.9.13 produces the following logs on start up and the integration remains in a "Not Loaded" state.  

Errors on startup:

```
Setup failed for custom integration google_home: Unable to import component: Exception importing custom_components.google_home
```
This error originated from a custom integration.

```
Logger: homeassistant.loader
Source: custom_components/google_home/api.py:11
Integration: Google Home (documentation, issues)
First occurred: 12:22:46 PM (88 occurrences)
Last logged: 12:25:01 PM

Unexpected exception importing component custom_components.google_home
Unexpected exception importing platform custom_components.google_home.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 599, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/google_home/__init__.py", line 17, in <module>
    from .api import GlocaltokensApiClient
  File "/config/custom_components/google_home/api.py", line 11, in <module>
    from glocaltokens.client import Device, GLocalAuthenticationTokens
  File "/usr/local/lib/python3.9/site-packages/glocaltokens/client.py", line 24, in <module>
    from .google.internal.home.foyer.v1_pb2 import GetHomeGraphRequest, GetHomeGraphResponse
  File "/usr/local/lib/python3.9/site-packages/glocaltokens/google/internal/home/foyer/v1_pb2.py", line 24, in <module>
    _GETASSISTANTROUTINESREQUEST = DESCRIPTOR.message_types_by_name[
KeyError: 'GetAssistantRoutinesRequest'
```

```
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 12:23:21 PM (87 occurrences)
Last logged: 12:25:01 PM

Error occurred loading configuration flow for integration google_home: Exception importing custom_components.google_home.config_flow
```

I tried removing the integration and reinstalling, but I need to downgrade to v.1.9.12 and then remove the integration before trying to setup again.  If I attempt to setup on v.1.9.13 I receive an error about the integration being unable to be setup in the UI.

One thing to note, I do also use the google wifi integration which I know has caused issues in the past.  Any ideas?

**Comment by KapJI** [comment] 2022-07-06 10:43
Can you check what version of `protobuf` you have installed? In virtualenv: `pip freeze | grep protobuf`

**Comment by DerekF35** [comment] 2022-07-06 12:34
Showing my work in case I ended up in the wrong place...

1) jumped into the `homeassistant` container using `docker exec -it homeassistant bash` 

2) executed first command you mentioned `pip freeze | grep protobuf` 
Output: 
 ```
bash-5.1# pip freeze | grep protobuf
protobuf==3.19.4
uplink-protobuf==0.1.0
```
Version looks correct.

3) Executed statements #2 
```
bash-5.1# pipdeptree -r --packages protobuf                                                                                                                                                                                                                           
Warning!!! Possibly conflicting dependencies found:                                                                                                                                                                                                                   
* aiobafi6==0.6.0                                                                                                                                                                                                                                                     
 - protobuf [required: >=3.20,<3.21, installed: 3.19.4]                                                                                                                                                                                                               
* ibm-watson==5.2.2                                                                                                                                                                                                                                                   
 - websocket-client [required: ==1.1.0, installed: 1.3.3]
* meteofrance-api==1.0.2
 - pytz [required: >=2020.4,<2022.0, installed: 2022.1]
* mycroftapi==2.0
 - websocket-client [required: ==0.44.0, installed: 1.3.3]
* pysmarty==0.8
 - pymodbus [required: ==1.5.2, installed: 2.5.3]
* surepy==0.7.2
 - async-timeout [required: >=3.0.1,<4.0.0, installed: 4.0.2]
------------------------------------------------------------------------
Warning!! Cyclic dependencies found:
* gps3 => gps3 => gps3
------------------------------------------------------------------------
protobuf==3.19.4
  - aiobafi6==0.6.0 [requires: protobuf>=3.20,<3.21]
  - aioesphomeapi==10.10.0 [requires: protobuf>=3.12.2,<4.0]
  - devolo-plc-api==0.8.0 [requires: protobuf]
  - gcloud==0.18.3 [requires: protobuf>=3.0.0b2,!=3.0.0.b2.post1]
    - Pyrebase4==4.5.0 [requires: gcloud>=0.18.3]
      - thermoworks-smoke==0.1.8 [requires: pyrebase4>=4.3.0]
  - google-api-core==2.8.2 [requires: protobuf>=3.15.0,<5.0.0dev]
    - google-api-python-client==2.38.0 [requires: google-api-core>=1.21.0,<3.0.0dev]
    - google-cloud-pubsub==2.11.0 [requires: google-api-core>=1.31.5,<3.0.0dev,!=2.3.0,!=2.2.*,!=2.1.*,!=2.0.*]
      - google-nest-sdm==1.8.0 [requires: google-cloud-pubsub>=2.1.0]
    - google-cloud-texttospeech==2.11.0 [requires: google-api-core>=1.31.5,<3.0.0dev,!=2.3.0,!=2.2.*,!=2.1.*,!=2.0.*]
  - googleapis-common-protos==1.56.3 [requires: protobuf>=3.15.0,<5.0.0dev]
    - gcloud==0.18.3 [requires: googleapis-common-protos]
      - Pyrebase4==4.5.0 [requires: gcloud>=0.18.3]
        - thermoworks-smoke==0.1.8 [requires: pyrebase4>=4.3.0]
    - google-api-core==2.8.2 [requires: googleapis-common-protos>=1.56.2,<2.0dev]
      - google-api-python-client==2.38.0 [requires: google-api-core>=1.21.0,<3.0.0dev]
      - google-cloud-pubsub==2.11.0 [requires: google-api-core>=1.31.5,<3.0.0dev,!=2.3.0,!=2.2.*,!=2.1.*,!=2.0.*]
        - google-nest-sdm==1.8.0 [requires: google-cloud-pubsub>=2.1.0]
      - google-cloud-texttospeech==2.11.0 [requires: google-api-core>=1.31.5,<3.0.0dev,!=2.3.0,!=2.2.*,!=2.1.*,!=2.0.*]
    - grpc-google-iam-v1==0.12.4 [requires: googleapis-common-protos>=1.56.0,<2.0.0dev]
      - google-cloud-pubsub==2.11.0 [requires: grpc-google-iam-v1>=0.12.3,<0.13dev]
        - google-nest-sdm==1.8.0 [requires: google-cloud-pubsub>=2.1.0]
    - grpcio-status==1.46.1 [requires: googleapis-common-protos>=1.5.5]
      - google-cloud-pubsub==2.11.0 [requires: grpcio-status>=1.16.0]
        - google-nest-sdm==1.8.0 [requires: google-cloud-pubsub>=2.1.0]
  - grpcio-status==1.46.1 [requires: protobuf>=3.12.0]
    - google-cloud-pubsub==2.11.0 [requires: grpcio-status>=1.16.0]
      - google-nest-sdm==1.8.0 [requires: google-cloud-pubsub>=2.1.0]
  - hangups==0.4.18 [requires: protobuf>=3.1.0,<4]
  - lakeside==0.12 [requires: protobuf]
  - proto-plus==1.20.6 [requires: protobuf>=3.19.0,<5.0.0dev]
    - google-cloud-pubsub==2.11.0 [requires: proto-plus>=1.15.0]
      - google-nest-sdm==1.8.0 [requires: google-cloud-pubsub>=2.1.0]
    - google-cloud-texttospeech==2.11.0 [requires: proto-plus>=1.15.0]
  - pyatv==0.10.0 [requires: protobuf>=3.19.1,<4]
  - PyChromecast==12.1.3 [requires: protobuf>=3.19.1]
  - pycomfoconnect==0.4 [requires: protobuf>=3.0.0]
  - python-clementine-remote==1.0.1 [requires: protobuf]
  - uplink-protobuf==0.1.0 [requires: protobuf]
    - solaredge-local==0.2.0 [requires: uplink-protobuf]
```

I have new hardware arriving tomorrow and I decided I'd do a fresh setup instead of restoring a backup, so that might end up fixing up whatever is the issue.  Everything was running smooth until I had an issue and needed to restore on the current hardware.  Happy to help continue debugging if it helps the devs or anyone else having this issue.

**Comment by DerekF35** [comment] 2022-07-06 15:20
Thanks for trying.  I'll stay pinned to v1.9.12 until I rebuild and we'll see what happens.

**Comment by DerekF35** [comment] 2022-07-09 13:21
After rebuild the issue is still occurring but I think I've found some evidence that is it related to https://github.com/djtimca/hagooglewifi integration.  ha-google-home will start fine if hagooglewifi is disabled during startup.  If hagooglewifi is then enabled after ha-google-home is started, both will work fine together.  Maybe something with the startup order.  I'm not sure if I can control that.

**Comment by nathang21** [comment] 2022-07-09 16:39
I'm having the exact same issue, I keep downgrading to avoid the issue (not sure why but I can't stop the auto upgrade).

I'm not aware of any clever way to control the order of operations for integrations to start. Addons can easily be controlled via scripts as I've had to do that as worksround for an unrelated issue previously.

**Comment by DerekF35** [comment] 2022-07-11 13:16
Reopening this issue as the conflict seems to manifest here and not with Google Wifi integration.  In the past, we've seen the actual cause be with the hagooglewifi repo but I haven't found evidence yet.  I've tried multiple scenarios to get the issue to appear on that side of the fence and see the google home integration load successfully, but no luck.

Work around is to disable Google Wifi, restart Home Assistant, and then once all integrations are loaded re-enabling Google Wifi.

**Comment by Dutchy-79** [comment] 2022-07-14 08:12
Same issue and also run Google Wi-Fi.

**Comment by DerekF35** [comment] 2022-07-15 17:40
After upgrading HACS to 1.26.2 my issue appears to have gone away, but I can't point to why.  I've restarted a few times and it starts clean.

Anyone else having the same experience after upgrading HACS?  Am I just getting lucky on restarts?

**Comment by Eeems** [comment] 2022-07-15 17:43
> After upgrading HACS to 1.26.2 my issue appears to have gone away, but I can't point to why. I've restarted a few times and it starts clean.
> 
> Anyone else having the same experience after upgrading HACS? Am I just getting lucky on restarts?

I've updated, but no luck.

**Comment by DerekF35** [comment] 2022-07-15 17:44
I spoke too soon.  After testing with 5 restarts and google_home loading fine for all 5, #6 google_home would not load with same error.

**Comment by Dutchy-79** [comment] 2022-07-18 10:34
> @KapJI, it looks like `KeyError` issue is being raised in our generated proto files. Do you think regenerating these could be a possible solution? (i have regenerated them locally, just to see for any changes, but they are a pain to diff compare) 😅

Try this

https://compare-it.en.softonic.com/

**Comment by KapJI** [comment] 2022-07-18 10:47
I guess the issue is `google-wifi` also has generated bindings for the same proto file. Protobuf has global buffer and different versions of these generated files cause issues.

The proper way to fix this is to extract generated files to the external package and use it both in `glocaltokens` and `google-wifi`. This way both integrations will be use exactly the same version of these files. Not sure I have time for this.

Quick fix will be reverting my recent update and try not to touch these files again.

**Comment by KapJI** [comment] 2022-07-18 21:36
It should be fixed in v1.9.14, please check it.

**Comment by Dutchy-79** [comment] 2022-07-18 22:32
Installed and no error after reboot so I think it's fixed indeed.

**Comment by DerekF35** [comment] 2022-07-19 00:17
Installed v1.9.14 also and performed a couple reboots.  Google home loaded correctly.

**Comment by leikoilja** [comment] 2022-07-19 07:11
Awesome! Thanks @KapJI for the fix 💪 🔥

**Closed by leikoilja** 2022-07-19 07:11 UTC
Labels: bug
