### ISSUE TITLE
server error after update to HA 2022.2.1

### ISSUE THREAD

**Issue by lecrams** [leikoilja/ha-google-home#454] opened 2022-02-04 09:15 UTC
After update to version 2022.2.1 I get the following error: "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble". Till this update everything was fine.
trying to reinstall I get exactly the same error. Has something changed with the update?
Any idea how to solve this?

**Comment by KapJI** [comment] 2022-02-04 10:21
Duplicate of https://github.com/leikoilja/ha-google-home/issues/453.

**Closed by KapJI** 2022-02-04 10:21 UTC
