### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_sorted_alarms

### ISSUE THREAD

**Issue by DurgNomis-drol** [leikoilja/ha-google-home#97] opened 2021-03-21 09:12 UTC
## Version of the custom_component

Latest

## Configuration

```yaml
2021-03-21 09:41:29 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 126, in _handle_refresh_interval
    await self.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 200, in async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 260, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 319, in _async_write_ha_state
    sstate = self.state
  File "/config/custom_components/google_home/sensor.py", line 141, in state
    alarms = self._get_alarms_data()
  File "/config/custom_components/google_home/sensor.py", line 156, in _get_alarms_data
    return self.as_dict(device.get_sorted_alarms())
AttributeError: 'NoneType' object has no attribute 'get_sorted_alarms'
```

## Describe the bug

It does not appear immediately, but shows up after my HA installation have been running for some hours. 

@leikoilja Have also had this error show up in his logs

**Comment by DurgNomis-drol** [comment] 2021-03-23 20:11
Why does this error only happen for alarms and not timers? I haven been looking through the code and can't find any differences between `get_sorted_alarms` and `get_sorted_timers`. 

@KapJI Any idea?

**Comment by leikoilja** [comment] 2021-03-23 20:23
Hmmm, just looked at its implementation and it's quite pythonic that we use `next` there. Don't really know in-depth how it's works, but if it's a shared `get_device` method that uses `next` to return next element from the iterator, would it actually reach end of iterator and return `None` at some point? Should it not just create a new iterator every time we call `get_device`? If it's **not** creating a new iterator and iterates all over-again every time we call it - that that's a problem... @KapJI, do you know how iterator and `next` works under the hood? :D Maybe we should just replace it with pseudo: "find in list and return the first element" instead ?

**Comment by KapJI** [comment] 2021-03-24 12:26
I guess we need some extra logging here. Maybe for some reason `coordinator_data` doesn't contain entry for this `device_name`.

@DurgNomis-drol are you able to reproduce this? Can you check if `next()` is doing something weird or `coordinator_data` doesn't contain `device_name`?

**Comment by DurgNomis-drol** [comment] 2021-03-24 13:16
This error only occurs after some time for me. I not 100% where i should log, so it is gonna be some trial and error for me 😄 Will report back when i have more information

**Comment by leikoilja** [comment] 2021-03-25 15:20
@DurgNomis-drol, let's keep an eye if we'll still have that bug. @KapJI did some [awesome work](https://github.com/leikoilja/ha-google-home/pull/111) rewriting how we get the device in the entity and I believe it might solve the issue if it was caused by `next` and iterator. When #111 is merged, let's install `master` version and keep an eye for a few ways :)

**Closed** 2021-03-25 18:46 UTC
Labels: bug
