### ISSUE TITLE
I'm using HA OS, and its not installing the python library `glocaltokens` - which appears to be failing on the install of `grpcio`

### ISSUE THREAD

**Issue by ArnyminerZ** [leikoilja/ha-google-home#101] opened 2021-03-22 10:23 UTC
I'm using HA OS, and its not installing the python library `glocaltokens` - which appears to be failing on the install of `grpcio`

```
FileNotFoundError: [Errno 2] No such file or directory: 'c++'
```

_Originally posted by @bacco007 in https://github.com/leikoilja/ha-google-home/issues/93#issuecomment-803814517_

**Comment by ArnyminerZ** [comment] 2021-03-22 10:29
@bacco007 please, check that you are using the latest version of the integration. Also, check the version you have installed of the `glocaltokens` python package.
You can do this through a SSH terminal ([guide here](https://siytek.com/home-assistant-shell/)), then, please type `pip3 show glocaltokens` in the terminal, and post the result here.

**Comment by DurgNomis-drol** [comment] 2021-03-22 12:21
@bacco007 What version of HAOS are you running and on what Architecture? (ARM, x86/x64)?

**Comment by leikoilja** [comment] 2021-03-22 15:34
I am pretty sure this error might occur on the elder versions of HomeAssistant OS.

**Comment by KapJI** [comment] 2021-03-22 19:18
The pinned version of `grpcio` is being built from sources and it probably needs `build-essential` package installed.

**Comment by DurgNomis-drol** [comment] 2021-03-22 20:08
`grpcio` needs both `g++` and `build-essential` to be able to build. On older versions then 2021.3 `g++` is missing. I don't know when `build-essential` were add to the HA.

Anyways this is known issue that have been fixed sometime ago. He should not have this problem if he is running the newest version anyway. 😄

**Comment by bacco007** [comment] 2021-03-23 06:46
> please, check that you are using the latest version of the integration.

Yes - v1.0.0

> `pip3 show glocaltokens` in the terminal, and post the result here.

```
Collecting glocaltokens
  Using cached glocaltokens-0.2.5.tar.gz (30 kB)
Collecting gpsoauth
  Using cached gpsoauth-0.4.3.tar.gz (5.1 kB)
Collecting grpcio==1.31.0
  Using cached grpcio-1.31.0.tar.gz (20.0 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qp3muz3y/grpcio_3b4233c30aeb4732b59fdfbb0eee15f8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qp3muz3y/grpcio_3b4233c30aeb4732b59fdfbb0eee15f8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6oh__gz5
         cwd: /tmp/pip-install-qp3muz3y/grpcio_3b4233c30aeb4732b59fdfbb0eee15f8/
    Complete output (13 lines):
    /tmp/pip-install-qp3muz3y/grpcio_3b4233c30aeb4732b59fdfbb0eee15f8/src/python/grpcio/commands.py:104: SyntaxWarning: "is not" with a literal. Did you mean "!="?
      if exit_code is not 0:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qp3muz3y/grpcio_3b4233c30aeb4732b59fdfbb0eee15f8/setup.py", line 197, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-install-qp3muz3y/grpcio_3b4233c30aeb4732b59fdfbb0eee15f8/setup.py", line 154, in check_linker_need_libatomic
        cc_test = subprocess.Popen(['cc', '-x', 'c++', '-std=c++11', '-'],
      File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.8/subprocess.py", line 1706, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cc'
    ----------------------------------------
```

> What version of HAOS are you running and on what Architecture? (ARM, x86/x64)?

HA OS 5.12 (OVA) via Proxmox VM

**Comment by leikoilja** [comment] 2021-03-23 07:21
@bacco007, I believe the problem is most likely in the fact that you are using `Proxmox VM` that is lacking system packages/compilers to deal with grpcio. 

> Depending on what operating system you are running your HomeAssistant instance
> on, you might need to install additional system-wide packages/compilers in order to
> be able to build wheels for `glocaltokens` python package, that is used by this
> integration.
> 
> Please SSH to your system and run:
> 
> - On Raspberry Pi (which most likely runs on Alpine Linux)
> 
> `apk add gcc g++ linux-headers`
> 
> - On Ubuntu
> 
> `sudo apt install build-essential`

Can you please try installing `build-essential` on your system first and then trying to reinstall the integration?
Keep us updated please

**Comment by bacco007** [comment] 2021-03-23 07:50
> I believe the problem is most likely in the fact that you are using Proxmox VM that is lacking system packages/compilers to deal with grpcio.

Proxmox simply allows me to run it via a VM self-contained - HA OS doesn't (to my knowledge) have the ability to install additional packages/compilers.

**Comment by leikoilja** [comment] 2021-03-23 07:59
Please see [here](https://developers.home-assistant.io/docs/operating-system/debugging/) how to get ssh access to the host in RPi example. Once you are on the host system which is probs Alpine try installing `apk add gcc g++ linux-headers`. I have done that with RPi and it fixed it, but not sure how your setup with Proxmox works :/

**Comment by DurgNomis-drol** [comment] 2021-03-23 18:42
I will setup a test machine and see if i can sort this out. 😄

**Comment by DurgNomis-drol** [comment] 2021-03-23 19:35
@bacco007 

I just did a fresh install of HAOS in VirtualBox as describe in HA's installation guide. I add HACS. Had some unrelated issues, fixed them. Added this integration through the normal repository and logged in and it work for me. I don't have a machine to install `proxmox` on and test it. But it should not differ from my test as a VM should be a VM as long as it is running on the same architecture. 

I will need some more information about what you have done to your setup to understand what is different about yours.

You should be able to install it anyways if you follow @leikoilja instructions 😄

**Comment by bacco007** [comment] 2021-03-24 08:31
Took me an hour - but i've been able to install the dependencies!

Now get a new error - havent had a chance to chase it out, run out of time today

```
2021-03-24 19:29:51 ERROR (SyncWorker_54) [glocaltokens.client] [!] Could not get master token.
2021-03-24 19:29:51 ERROR (MainThread) [custom_components.google_home] 
```

**Comment by leikoilja** [comment] 2021-03-24 09:32
okay okay, we are getting closer, @bacco007. Regarding the error you see now - we need to look deeper into that, you seem not be the only one with it:
https://github.com/leikoilja/ha-google-home/issues/95
the gears are in move, so just bare with us

**Comment by KapJI** [comment] 2021-03-24 09:35
@bacco007 what issues did you have? Maybe we can document them and this will be useful for others?

**Comment by DurgNomis-drol** [comment] 2021-03-24 11:46
@bacco007 [Here](https://github.com/bacco007/HomeAssistantConfig#stats) you list that you are using HA core 2021.1.5. Is this the version which are using now and are trying to install on?

**Comment by bacco007** [comment] 2021-03-25 06:51
> what issues did you have with installation and how did you solve them?

I had what I'm guessing was an issue with my internet, it didnt download the dependencies properly then failed to install properly the first time around.  It also had to build a couple of them which took a little bit of time.

> Here you list that you are using HA core 2021.1.5. Is this the version which are using now and are trying to install on?

I'm now on 2021.3.4 - my readme file hasnt updated for a while by the look of it, need to fix that!

**Comment by leikoilja** [comment] 2021-03-25 10:05
@bacco007, since now you are facing `login` issue that is the same as #95, I ll close this issue. :) Hope all the rest of your issues are fixed now :)
Feel free to open new issues per each problem you encounter so that we can help it :)

**Closed by leikoilja** 2021-03-25 10:05 UTC
Labels: bug, question
