### ISSUE TITLE
I cannot configure the component after install

### ISSUE THREAD

**Issue by BernieV1977** [leikoilja/ha-google-home#245] opened 2021-05-31 12:01 UTC
## Describe the bug

When I enter my Google account and application password I got an "Unknown error occured"

## Version of the integration

If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
1.4.3

## Logs

<!-- To enable debug logs, put the below snippet in your configuration.yaml file.

logger:
  default: debug
  logs:
    custom_components.google_home: debug
-->

<!-- Paste logs below here-->

```text
2021-05-31 13:48:16 WARNING (MainThread) [homeassistant.components.http.security_filter] Filtered a request with a potential harmful query string: /devices.inc.php?search=True&searchField=antani'+union+select+(select+concat(0x223e3c42523e5b70726f6a6563742d646973636f766572795d)+limit+0,1),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL+--+&searchColumn=n.id&searchOption=contains
2021-05-31 13:50:32 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.8.10/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/home/homeassistant/.pyenv/versions/3.8.10/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.8.10/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.8.10/lib/python3.8/site-packages/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.8.10/lib/python3.8/site-packages/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.8.10/lib/python3.8/site-packages/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.8.10/lib/python3.8/site-packages/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/home/homeassistant/.pyenv/versions/3.8.10/lib/python3.8/site-packages/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/home/homeassistant/.pyenv/versions/3.8.10/lib/python3.8/site-packages/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/home/homeassistant/.pyenv/versions/3.8.10/lib/python3.8/site-packages/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/home/homeassistant/.pyenv/versions/3.8.10/lib/python3.8/site-packages/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/home/homeassistant/.pyenv/versions/3.8.10/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 199, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/home/homeassistant/.pyenv/versions/3.8.10/lib/python3.8/site-packages/homeassistant/data_entry_flow.py", line 257, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/mnt/dietpi_userdata/homeassistant/custom_components/google_home/config_flow.py", line 59, in async_step_user
    master_token = await self._test_credentials(client)
  File "/mnt/dietpi_userdata/homeassistant/custom_components/google_home/config_flow.py", line 92, in _test_credentials
    master_token = await client.async_get_master_token()
  File "/mnt/dietpi_userdata/homeassistant/custom_components/google_home/api.py", line 71, in async_get_master_token
    master_token = await self.hass.async_add_executor_job(_get_master_token)
  File "/home/homeassistant/.pyenv/versions/3.8.10/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/dietpi_userdata/homeassistant/custom_components/google_home/api.py", line 69, in _get_master_token
    return self._client.get_master_token()
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.8/site-packages/glocaltokens/client.py", line 247, in get_master_token
    res = perform_master_login(
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.8/site-packages/gpsoauth/__init__.py", line 139, in perform_master_login
    return _perform_auth_request(data, proxy)
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.8/site-packages/gpsoauth/__init__.py", line 80, in _perform_auth_request
    session.mount(AUTH_URL, AuthHTTPAdapter())
  File "/home/homeassistant/.pyenv/versions/3.8.10/lib/python3.8/site-packages/requests/adapters.py", line 129, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "/mnt/dietpi_userdata/homeassistant/deps/lib/python3.8/site-packages/gpsoauth/__init__.py", line 71, in init_poolmanager
    context.post_handshake_auth = True
AttributeError: attribute 'post_handshake_auth' of '_ssl._SSLContext' objects is not writable
![Knipsel](https://user-images.githubusercontent.com/16529684/120190296-b1079580-c218-11eb-8395-fd22463e2991.JPG)

```

**Comment by KapJI** [comment] 2021-06-01 09:02
You have incompatible version of OpenSSL installed.

From https://docs.python.org/3/library/ssl.html#ssl.SSLContext.post_handshake_auth:
> Note Only available with OpenSSL 1.1.1 and TLS 1.3 enabled. Without TLS 1.3 support, the property value is None and can’t be modified

**Comment by BernieV1977** [comment] 2021-06-01 13:18
I have upgrade OpenSSL: openssl version
OpenSSL 1.1.1g  21 Apr 2020

On my Windows 10 client TLS 1.3 is enabled but I got the same error when I try again.

**Comment by KapJI** [comment] 2021-06-01 13:26
Apparently your python doesn't use it. You can check it by running this in python interpreter:
```python
>>> import ssl
>>> ssl.HAS_TLSv1_3
True
```

**Comment by BernieV1977** [comment] 2021-06-01 14:12
My HA install is running in a virtual Python environment pyenv. (HA runs on DietPi) How should I test your commands in that virtual Pyhton environment?

**Comment by KapJI** [comment] 2021-06-01 14:26
You can activate that virtualenv, usually it's done by running in venv folder:
```shell
source bin/activate
python
```

**Comment by BernieV1977** [comment] 2021-06-03 06:23
Python 3.8.10 (default, May 15 2021, 17:52:29)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.HAS_TLSv1_3
False
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.1.0l  10 Sep 2019'

So, in the virtual Python enivronment the old opssl version is still active without tls1.3
Do you know make openssl 1.1.1 also active in the virtual python environment?
Tia

**Comment by KapJI** [comment] 2021-06-03 11:22
Try this: `pip install 'openssl==1.1.1' --force-reinstall`

Or you may need to delete old openssl version and reinstall python.

**Comment by BernieV1977** [comment] 2021-06-05 09:15
After doing an inplace uprage from stretch to buster is't now possible to configure the integration. All my devices Google Home devices are in HA now.
Is it normal that all the devices entities of timers and alarms are in unavailable state?

**Comment by ArnyminerZ** [comment] 2021-06-06 15:54
@BernieV1977 if you don't have any alarms nor timers configured, yeah, it's normal. Try configuring some alarms, and check again if the entity's value has changed.

**Comment by BernieV1977** [comment] 2021-06-06 20:26
OK, thx for it

> @BernieV1977 if you don't have any alarms nor timers configured, yeah, it's normal. Try configuring some alarms, and check again if the entity's value has changed.

OK, thx

**Comment by KapJI** [comment] 2021-06-07 12:22
Assuming the issue is resolved with distro upgrade.

**Closed by KapJI** 2021-06-07 12:22 UTC
Labels: question

**Comment by leikoilja** [comment] 2021-06-07 13:36
Awesome, thanks @KapJI for some good insights regarding TLS support, good to know for further debugging
