### ISSUE TITLE
Can't Authenticate using app password.  

### ISSUE THREAD

**Issue by bagelos** [leikoilja/ha-google-home#675] opened 2023-03-06 07:52 UTC
## Describe the bug
Can't Authenticate the google_home integration in HA.  
I have looked at various old similar issues and tried the resolutions there.  None have worked.  
Issue appears to be Cannot authenticate.  
Have previously had this configured though.  
Rebuilt server moving to Ubuntu 22.04 and never been able to reconfigure.  
Also tried the following but would not work due to issue getting MAC address.  
I included the MAC address of a google home on my network and also output from logs above and output is below.

python3.11 get_tokens.py

This script generates tokens that can be used when making requests to the Google Home Foyer API.
There are 2 kinds of tokens used here:
1. Master token - Is in the form `aas_et/***` and is long lived. Needs Google username and password.
2. Access token - Is in the form `ya29.***` and lasts for an hour. Needs Master token to generate.
If you do not want to store the Google account password in plaintext,
get the master token once, and set it as an override value.
It's safer/easier to generate an app password and use it instead of the actual password.
It still has the same access as the regular password, but still better than using the real password while scripting.
(https://myaccount.google.com/apppasswords)

[*] Getting master token...
[!] Could not get master token.
[*] Master token: None

[*] Getting access token...
[!] Could not get access token.
[*] Access token: None

[*] Done.

To replicate 

add google_home integration via HACS
restart ha
attempt to configure integration and authenticate
add username (without @gmail.com) and use app password

## Version of the integration
If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```text
1.9.17
glocaltokens==0.7.0
gpsoauth==1.0.2
requests==2.28.2
requests-toolbelt==0.10.1
urllib3==1.26.14
uuid==1.30
```

## Logs

```text
2023-03-06 18:40:51.369 DEBUG (MainThread) [glocaltokens.client] Initializing new GLocalAuthenticationTokens instance.
2023-03-06 18:40:51.369 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client access_token, homegraph, access_token_date and homegraph_date to None
2023-03-06 18:40:51.370 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client username to "******", password to "***************", master_token to "" and android_id to
2023-03-06 18:40:51.370 DEBUG (SyncWorker_6) [glocaltokens.client] There is no stored master_token, logging in using username and password
2023-03-06 18:40:51.370 DEBUG (SyncWorker_6) [glocaltokens.client] There is no stored android_id, generating a new one
2023-03-06 18:40:51.370 DEBUG (SyncWorker_6) [glocaltokens.client] Generating android id...
2023-03-06 18:40:51.371 DEBUG (SyncWorker_6) [glocaltokens.client] Generated android id: a7574b3e185fd258
2023-03-06 18:40:52.826 ERROR (SyncWorker_6) [glocaltokens.client] [!] Could not get master token.
2023-03-06 18:40:52.827 DEBUG (SyncWorker_6) [glocaltokens.client] Request response: {'Error': 'BadAuthentication'}
2023-03-06 18:40:52.828 ERROR (MainThread) [custom_components.google_home]
```

**Comment by leikoilja** [comment] 2023-03-06 10:07
Closed, because it's a duplicate of https://github.com/leikoilja/ha-google-home/issues/599

**Closed by leikoilja** 2023-03-06 10:07 UTC
