### ISSUE TITLE
Problems during first login

### ISSUE THREAD

**Issue by ManuelLR** [leikoilja/ha-google-home#90] opened 2021-03-12 20:09 UTC
## Versions
- **ha-google-home**: Error occur with `v1.0.0` and [latest commit on master](https://github.com/leikoilja/ha-google-home/commit/b51afaff56722c5b276000067bc8ea6e7941d651)
- **homeassistant/core**: 2021.3.3

### Google Account
Since I have 2FA enabled, I have created an application password.

### Home Assistant
This component does not need configuration in yaml format but you can check how to install it or the complete configuration in my repository: 
- Dockerfile (installation of component): https://github.com/ManuelLR/MomaHome/blob/e289ff9aa27c3b775fa0353f694de69f1d13403d/home_automation/home_assistant/Dockerfile#L22-L25

- Link to `custom_components` custom path: https://github.com/ManuelLR/MomaHome/blob/next/home_automation/home_assistant/config/custom_components

All the configuration and plugins work perfectly, only this one fails.

## Describe the bug

After installing the plugin, I tried to configure it but, after entering my login details, it fails with the following error:
```
 Username/Password is incorrect. If your google account has 2FA enabled please generate app password (https://myaccount.google.com/apppasswords) 
```
and in the home-assistant logs I can see the following:
```
Logger: glocaltokens.client
Source: /usr/local/lib/python3.8/site-packages/glocaltokens/client.py:169
First occurred: 8:42:50 PM (1 occurrences)
Last logged: 8:42:50 PM

[!] Could not get master token.
```

## Debug log
I tried to debug a bit more and discovered that [here](https://github.com/simon-weber/gpsoauth/blob/a7daa9250468161a44819e33e1eec8721b32e983/gpsoauth/__init__.py#L62) the variable `res` contain the value ` Error=BadAuthentication `.

I can probe further but first I wanted to know if this is a known bug since it seems to be related to https://github.com/simon-weber/gpsoauth/issues/24.

**Comment by leikoilja** [comment] 2021-03-13 06:53
Hey, @ManuelLR. 
You have a pretty cool way of installing components I would say 😄 
I have seen `BadAuthentiation` errors before on the systems where the python `requests` library is either of a too new version or too old ([ref](https://github.com/simon-weber/gpsoauth/issues/24#issuecomment-750922489)). I would assume it is something do to with dependencies and libraries on your Docker instance.

What I recommend you do now is try authentication in isolation away from your home assistant docker instance. You can do that by trying [glocaltokens](https://github.com/leikoilja/glocaltokens) python package(this integration uses `glocaltokens` under the hood) on your laptop/pc. It will allow you to make sure your username/password are right and the package returns all data as expected (see `example/get_tokens.py`). If that would work then you need to start looking at your Docker instance and environment where you are installing the integration. If the `glocaltokens` example will work in isolation, please post here your versions of `docker`, your `os`, and versions of python packages for `grpcio`, `grpcio-tools`, `requests` from the machine where you are installing this integration.

I know @DurgNomis-drol is successfully running the integration under docker instance. Maybe he can share some insights.

**Comment by DurgNomis-drol** [comment] 2021-03-13 08:40
Can you also provide the version info for: `gpsoauth`, `urllib3` and `chardet`. You can do this by running `pip show "package name"` in the docker container.

The error you're getting is caused by urllib3. See [here](https://github.com/urllib3/urllib3/issues/2101)

The problem you are referring to, was a known bug, but it should have been fixed in the version this integration uses.

**Comment by ManuelLR** [comment] 2021-03-13 09:16
I have been doing some research and I find it quite strange.

---
First, I created a Dockerfile to easily test the different configurations:
```Dockerfile
ARG python_version=3.8
FROM python:${python_version}

RUN pip install glocaltokens==0.2.4
RUN \
    set -ex \
    && apt-get update && apt-get install -y wget \
    && wget https://raw.githubusercontent.com/leikoilja/glocaltokens/master/example/get_tokens.py

CMD [ "python3", "get_tokens.py" ]
```
It's works without problems in the next scenarios:
```bash
# Python 3.8-slim (without gcc and others)
docker build --build-arg=python_version=3.8-slim -t my-glocaltoken-38-slim .
docker run --rm -it \
     -e GOOGLE_USERNAME -e GOOGLE_PASSWORD \
     my-glocaltokens-38-slim

# Python 3.8
docker build --build-arg=python_version=3.8 -t my-glocaltoken-38 .
docker run --rm -it \
     -e GOOGLE_USERNAME -e GOOGLE_PASSWORD \
     my-glocaltokens-38

# Python 3.9
docker build --build-arg=python_version=3.9 -t my-glocaltoken-39 .
docker run --rm -it \
     -e GOOGLE_USERNAME -e GOOGLE_PASSWORD \
     my-glocaltokens-39
```

But it's fails in the next scenario:
```bash
# Python 3.9-slim (without gcc and others)
docker build --build-arg=python_version=3.9-slim -t my-glocaltoken-39-slim .

```
That error is caused because some dependencies were not build for python 3.9 and need to be compiled. Not really important at all.

---
After executing that test I proceed to check the version of the dependencies on the HA image and the dependencies in the above container:

```diff
certifi==2020.12.5
- chardet==3.0.4
+ chardet==4.0.0
glocaltokens==0.2.4
gpsoauth==0.4.3
grpcio==1.31.0
grpcio-tools==1.31.0
idna==2.10
ifaddr==0.1.7
- protobuf==3.15.5
+ protobuf==3.15.6
pycryptodomex==3.10.1
requests==2.25.1
simplejson==3.17.2
six==1.15.0
urllib3==1.26.3
zeroconf==0.28.8
```
(red in HA, green on new container)

---
After see the differences I decide to test the file directly in HA:
```bash
docker exec -ti home_automation_home-assistant_1 bash
bash-5.0# wget https://raw.githubusercontent.com/leikoilja/glocaltokens/master/example/get_tokens.py
bash-5.0#   GOOGLE_USERNAME=xyz@gmail.com GOOGLE_PASSWORD=xyz python3 get_tokens.py 
.
.
  
[*] Master token suhdsuhfuhfudsjfjsdf 

[*] Access token (lives 1 hour) ya29.afhfdjfhdj

[*] Google devices local authentication tokens
WARNING:zeroconf:Error sending through socket 14
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 2952, in send
    bytes_sent = s.sendto(packet, 0, (real_addr, port))
OSError: [Errno 101] Network unreachable
[*] Google devices "json of valid devices with access token in my home"
```
So, the script work into HA container (with all custom_components installed and already initialized).

---
After check that the script is working,I have gone back to HA, put exactly the same credentials I used in the script and it does not work.

**Comment by leikoilja** [comment] 2021-03-13 10:15
Have you done all of those tests you mentioned on the same machine as you are running your HA container? I am wondering if you use the same architecture in all those cases?

**Comment by DurgNomis-drol** [comment] 2021-03-13 10:15
Indeed it seems very strange.

@ManuelLR  What system are you running docker on? I run mine on rp4 on OMV5 and i have not encountered this, so I'm very curios to understand what triggers it

**Comment by ManuelLR** [comment] 2021-03-13 10:31
I have HA container running on a server (AMD processor x86-64) at my home using Debian 10.

The tests installing directly the library on the Dockerfile have been executed in github codespace (a x86-64 virtual machine in Azure) but the latest test was executed directly onto HA container already running in my server (not a different container, i connected to the running container from which HA is served)

**Comment by DurgNomis-drol** [comment] 2021-03-13 11:42
Can you please try to downgrade `urllib3` to `1.25.11` and see if that helps.

**Comment by ManuelLR** [comment] 2021-03-13 12:59
Quick update, To test it, I deployed home-assistant on my local with the same container I use on the server but removing all unnecessary configuration from `configuration.yaml` to leave only ha-google-home and voila, it works.

**Comment by leikoilja** [comment] 2021-03-17 12:41
@ManuelLR, were you able to find the root of the issue and fix it? :)

**Comment by ManuelLR** [comment] 2021-03-17 15:11
No, I am having a lot of work and have not been able to dedicate much time to it.
Just yesterday I did another test but nothing remarkable, I repeat my last test in the server and works so it seems that it is not a Debian or similar problem. When I have some time I will test with all the active integrations to see if it is something strange with some integration.

**Comment by leikoilja** [comment] 2021-03-17 15:22
Sounds good, @ManuelLR. I will close this issue for now, since it seems to be package irrelevant. However, feel free to reopen if you will have some new finding that are important for us to take a look on. Also, just ping us here if there are any help needed ;)

**Closed by leikoilja** 2021-03-17 15:22 UTC

**Comment by ManuelLR** [comment] 2021-04-08 21:35
Just for your information, today I updated HA and the ingration to the latest releases (2021.4 and v1.3.0) and magically all works perfectly. I can configure the integration without problems, retrieve data and also delete timers.

Really thanks for your help here!

**Comment by KapJI** [comment] 2026-02-04 22:27
Check for workaround in https://github.com/leikoilja/ha-google-home/issues/987
