### ISSUE TITLE
Despite getting master token I cannot  login successfully

### ISSUE THREAD

**Issue by mmatesic01** [leikoilja/ha-google-home#877] opened 2024-06-09 13:16 UTC
## Describe the bug

I get the master token with  breph/ha-google-home_get-token. But despite that when carefully entering my google email and complete master token (copy/paste) it still won't let me log in successfully.

## Version of the integration
If you are unsure about the version check the [github release here](https://github.com/leikoilja/ha-google-home/releases).

```
Goohle Home, latest version 1.11.0
```

## Logs

```text
Add your logs here.
```

**Comment by franito16** [comment] 2024-06-09 16:10
Same problem here

**Comment by KapJI** [comment] 2024-06-09 18:03
Duplicate of #876

**Closed by KapJI** 2024-06-09 18:03 UTC
