### ISSUE TITLE
Failing to install due to glocaltokens dependancy (grpcio-tools)

### ISSUE THREAD

**Issue by ollioddi** [leikoilja/ha-google-home#14] opened 2021-02-08 14:01 UTC
Hi.

Im having trouble installing your addon, which btw is amazing work.
I followed the guide provided but when i launch homeassistant and try to setup the integration nothing happens. Multiple errors show up in the logs.

```
2021-02-08 14:54:18 ERROR (SyncWorker_1) [homeassistant.util.package] Unable to install package glocaltokens==0.1.4: ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2u_2xggr/grpcio-tools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2u_2xggr/grpcio-tools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-iz62u3yg
cwd: /tmp/pip-install-2u_2xggr/grpcio-tools/
Complete output (11 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-2u_2xggr/grpcio-tools/setup.py", line 151, in <module>
if check_linker_need_libatomic():
File "/tmp/pip-install-2u_2xggr/grpcio-tools/setup.py", line 80, in check_linker_need_libatomic
cpp_test = subprocess.Popen([cxx, '-x', 'c++', '-std=c++11', '-'],
File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'c++'
```
Not sure if this last error is regarding glocaltokens.
```
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
2021-02-08 14:54:18 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 136, in post
return await super().post(request)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post
result = await self._flow_mgr.async_init(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 119, in async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 541, in async_create_flow
await async_process_deps_reqs(self.hass, self._hass_config, integration)
File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in async_process_deps_reqs
await requirements.async_get_integration_with_requirements(
File "/usr/src/homeassistant/homeassistant/requirements.py", line 79, in async_get_integration_with_requirements
await async_process_requirements(
File "/usr/src/homeassistant/homeassistant/requirements.py", line 136, in async_process_requirements
raise RequirementsNotFound(name, [req])

```
Any suggestions? Could very well be my fault.

**Comment by leikoilja** [comment] 2021-02-08 15:36
Hey, @ollioddi. 
There is currently a problem with `grpcio-tools` and `grpcio` dependencies when running the package on `arm` based devices, like raspberry pi. That's why installation of `glocaltokens` fails when adding an addon in Home Assistant.
I currently don't have time to take a look at it but will try finding a solution in the next few days/week.

**Comment by ollioddi** [comment] 2021-02-08 17:52
Hey @leikoilja,

Thanks for the response. I get why it might not work on a raspberry pi, but my setup runs on a desktop x86 platform on ESXI using the official VM image.

**Comment by DurgNomis-drol** [comment] 2021-02-09 20:57
Try this in console/terminal: `apk add gcc g++ linux-headers` This makes it possible to compile grpcio-tools on raspberry pi. This problem exists because the docker image is based on alpine. I dont know if the official VM image also is based on alpine. But the error you get is because you are missing a c++ compiler.

**Comment by ollioddi** [comment] 2021-02-09 21:19
Hey @DurgNomis-drol,

Thank you very much. It did something but i am still getting some errors regarding c++. Any other suggestions?

I suppose that you are aware of this problem already, but i am eager to test it :)

```
2021-02-09 22:16:20 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package glocaltokens==0.1.4: ERROR: Command errored out with exit status 1:
command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zwmatuqo/grpcio-tools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zwmatuqo/grpcio-tools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cdok0267
cwd: /tmp/pip-install-zwmatuqo/grpcio-tools/
Complete output (11 lines):
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-install-zwmatuqo/grpcio-tools/setup.py", line 151, in <module>
if check_linker_need_libatomic():
File "/tmp/pip-install-zwmatuqo/grpcio-tools/setup.py", line 80, in check_linker_need_libatomic
cpp_test = subprocess.Popen([cxx, '-x', 'c++', '-std=c++11', '-'],
File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'c++'
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
2021-02-09 22:16:20 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 136, in post
return await super().post(request)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post
result = await self._flow_mgr.async_init(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 119, in async_init
flow = await self.async_create_flow(handler, context=context, data=data)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 541, in async_create_flow
await async_process_deps_reqs(self.hass, self._hass_config, integration)
File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in async_process_deps_reqs
await requirements.async_get_integration_with_requirements(
File "/usr/src/homeassistant/homeassistant/requirements.py", line 79, in async_get_integration_with_requirements
await async_process_requirements(
File "/usr/src/homeassistant/homeassistant/requirements.py", line 136, in async_process_requirements
raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for ha-glocaltokens not found: ['glocaltokens==0.1.4'].

**Comment by DurgNomis-drol** [comment] 2021-02-09 21:24
Try installing grpcio-tools manually in terminal. Run: `pip install grpcio-tools==1.31.0` Same versions as grpcio in Homeassistant. This may take some time depending on how fast your system are. On rpi it takes about 20 -30 minutes.

**Comment by ArnyminerZ** [comment] 2021-02-10 14:22
I have the same issue on the Home Assistant Docker installation in Windows using Docker. In my case, the error is as follows:
```shell
/config $ python3 -m pip install grpcio-tools==1.31.0
Collecting grpcio-tools==1.31.0
  Using cached grpcio-tools-1.31.0.tar.gz (2.1 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mm5qqn1q/grpcio-tools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mm5qqn1q/grpcio-tools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-4gueg1mq
         cwd: /tmp/pip-install-mm5qqn1q/grpcio-tools/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mm5qqn1q/grpcio-tools/setup.py", line 112, in <module>
        if check_linker_need_libatomic():
      File "/tmp/pip-install-mm5qqn1q/grpcio-tools/setup.py", line 73, in check_linker_need_libatomic
        cc_test = subprocess.Popen(['cc', '-x', 'c++', '-std=c++11', '-'],
      File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cc'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
*(Skipped pip version warning)*

**Comment by DurgNomis-drol** [comment] 2021-02-10 14:30
The problem is that Homeassistant docker is based upon Alpine. `grpcio grpcio-tools` buildwheels doesn't work with Alpine. @leikoilja have already made an issue with Homeassistant so we can make it work.

**Comment by leikoilja** [comment] 2021-02-13 08:56
To sum it up, the problem currently is that `glocaltokens` underlying package is relying on `grpcio==1.31.0` and `grpcio-tools`. Those two fail to build wheels because the operating system where HA is running is lacking additional compilers such as `gcc g++ linux-headers`. 
We have a separate issue for that under `glocaltokens` package: https://github.com/leikoilja/glocaltokens/issues/11

Since the issue is not directly related to **this** repo, I will lock this conversation to encourage everyone to move to https://github.com/leikoilja/glocaltokens/issues/11

**Comment by DurgNomis-drol** [comment] 2021-02-13 09:09
Agree, i will reply over at [glocaltokens](https://github.com/leikoilja/glocaltokens/issues/11)

**Comment by leikoilja** [comment] 2021-03-02 03:33
Happy to announce, this should be fixed now! 💥 
See [this thread](https://github.com/leikoilja/ha-google-home/discussions/23#discussioncomment-420354) for more information!

**Closed by leikoilja** 2021-03-02 03:33 UTC
Labels: glocaltokens
